{% set name = "findlibs" %}
{% set pypi_name = "findlibs" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 60a6b897369dda37fb0e2c63981e49e9bfadd435297b00085d64169aea1afc6b

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $(python -c "import site; print(site.getsitepackages()[0])")/findlibs/__init__.py  # [not win]

about:
  home: https://github.com/ecmwf/findlibs
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
  summary: Python package to search for shared libraries on various platforms

extra:
  recipe-maintainers:
    - iainrussell
